"Bundles

call plug#begin('~/.vim/plugged')

source ~/.vim/bundle/basicPlugins.vim
source ~/.vim/bundle/colorScheme.vim
source ~/.vim/bundle/extraPlugins.vim

call plug#end()


"Basic settings

source ~/.vim/base/global.vim
source ~/.vim/base/interface.vim
source ~/.vim/base/mappings.vim
source ~/.vim/base/optional.vim

source ~/.vim/base/local.vim


"Bundle settings
source ~/.vim/bundle/config/basicPlugins.vim
